### PR TITLE
Make Multipart\AbstractUploadManager accept PHP 7+ Throwable as a failure type

### LINKED ISSUE #1755: TypeError: Argument 1 of Aws\Multipart\AbstractUploadManager::Aws\Multipart\{closure}() must be an instance of Exception, instance of Error given
The `AbstractUploadManager` is catching `Exception` types, however, if a PHP 7.0+ `Error` is thrown, the actual error that occurred is suppressed by the registered error handler of the promise. 

https://github.com/aws/aws-sdk-php/blob/bccb5b3509ed7517e50a75bba6b19ac4506aae70/src/Multipart/AbstractUploadManager.php#L140-L146

### PR DESCRIPTION
**Pull request by bradynpoulsen**
Closes #1755
#  ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

Requesting a pull to aws:master from bradynpoulsen:bug/1755_php_7_throwable_support_by_multipart_abstractuploadmanager

Write a message for this pull request. The first block
of text is the title and the rest is the description.

### CODE REVIEW

File: src/Multipart/AbstractUploadManager.php [hunk 1]
```diff
@@ -137,13 +137,29 @@ public function promise()
...
+        // Throw errors from the operations as a specific Multipart error.
+        if ($e instanceof AwsException) {
+            $e = new $this->config['exception_class']($this->state, $e);
+        }
+        throw $e;
+    }
+
+    private function buildFailureCatch()
+    {
+        if (PHP_MAJOR_VERSION >= 7) {
```
Comment (bradynpoulsen) [inline src/Multipart/AbstractUploadManager.php]: This may be overkill, but I did want to propose a solution that kept the type-checking instead of just dropping it in favor of a naked `otherwise(function ($e)`

Comment (srchase) [reply src/Multipart/AbstractUploadManager.php]: @bradynpoulsen 

This solution makes sense to keep type-checking here.  Could you add test coverage for this change?  

Also, instead of checking ```PHP_MAJOR_VERSION``` we could check Throwable directly: 
```
if (interface_exists('Throwable')) {
```

Comment (srchase) [reply src/Multipart/AbstractUploadManager.php]: checking in again.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 # CHANGELOG
 
+## 3.92.2 - TBD
```
Comment (srchase) [inline CHANGELOG.md]: Refer to the instructions for adding a changelog here: [CONTRIBUTING - changelog](https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md#changelog-documents).

This will get added to CHANGELOG.md automatically in the right release.

Comment (bradynpoulsen) [reply CHANGELOG.md]: That makes sense! Fixed, thanks :)
