### PR TITLE
PHP 8.0, 8.1, PHPUnit 9 support + automated check for php compatibility

### LINKED ISSUE #2378: PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
```
PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///Users/foo/aws/aws.phar/Aws/Api/Serializer/Ec2ParamBuilder.php on line 15
```

**Version of AWS SDK for PHP?**
3.209.28
**Version of PHP (`php -v`)?**
8.1.2

**To Reproduce (observed behavior)**
Use any API in Aws\Ec2\Ec2Client

**Expected behavior**
I expect AWS SDK to work with the latest PHP version and produce no deprecation warnings/errors

### PR DESCRIPTION
**Pull request by Zombaya**
I've expanded on the excellent work done by @27pchrisl  in PR #2332.  I rebased his branch onto the latest version of master, upgraded the new tests to be able to use phpunit 9 and added a new CI-job that lints all code in `src` to make sure it is compatible with all supported versions of php (5.5-8.1) using [phpcompatibility](https://github.com/PHPCompatibility/PHPCompatibility).

This should add support for php 8.0 and php 8.1 to the project and make sure no code will trigger bugs because of changes in php.

This should probably fix #2378, #2367

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stobrien89** [comment]
Hi @Zombaya and @27pchrisl,

Thanks a lot for all of the work on this.  @SamRemis and I will review when we have a chance, which will take some time. We'll get back to you ASAP, likely by the end of next week.

**Comment by Zombaya** [comment]
Very much looking forward to it :-).  If I can be of any help, please let me know and I'll try to take some time to help.

File: tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+    {
+        $this->assertContains($expected, $actual, $message);
+    }
+
+    public function assertStringNotContainsString($expected, $actual, $message = '')
+    {
+        $this->assertNotContains($expected, $actual, $message);
+    }
+
+    public function assertStringContainsStringIgnoringCase($expected, $actual, $message = '')
```
Comment (SamRemis) [inline tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php:87]: Same as above assertStringContainsIgnoreCase()

File: src/MockHandler.php [hunk 2]
```diff
@@ -37,7 +37,7 @@ public function __construct(
         $this->onRejected = $onRejected;
 
         if ($resultOrQueue) {
-            call_user_func_array([$this, 'append'], $resultOrQueue);
+            call_user_func_array([$this, 'append'], array_values($resultOrQueue));
```
[the remark this answers is not in the document]
Comment (27pchrisl) [reply src/MockHandler.php:40]: This is in place for the PHP 8 named params change, where in PHP7 for call_user_func_array() array keys were ignored. Now, string keys will be interpreted as parameter names. The simple solution is to strip keys using array_values.

File: tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+        $exception = $this->getExpectedException();
+        $this->setExpectedExceptionRegExp($exception, $messageRegExp, $this->exceptionCode);
+    }
+
+    public function assertStringContainsString($expected, $actual, $message = '')
+    {
+        $this->assertContains($expected, $actual, $message);
+    }
+
+    public function assertStringNotContainsString($expected, $actual, $message = '')
```
[the remark this answers is not in the document]
Comment (27pchrisl) [reply tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php:82]: Agreed it is long! But it's new in phpunit (https://phpunit.readthedocs.io/en/9.5/assertions.html#assertstringcontainsstring). And PhpStorm includes a linter rule to hint it should be used. However, it is certainly dealer's choice so we could revert this.

File: src/Crypto/AesGcmDecryptingStream.php [hunk 4]
```diff
@@ -83,6 +83,7 @@ public function createStream()
                 $this->keySize
             ));
         } else {
+            // phpcs:ignore PHPCompatibility.FunctionUse.NewFunctionParameters -- False positive, never used in php <= 7.0
```
[the remark this answers is not in the document]
Comment (27pchrisl) [reply src/Crypto/AesGcmDecryptingStream.php:86]: In my loosely held opinion in the tests is best, as then your rules and your tests are right next to each other in your editor view.

File: .github/workflows/tests.yml [hunk 5]
```diff
@@ -39,34 +39,48 @@ jobs:
...
-    - if: ${{ matrix.php-versions >= '7.1' && matrix.php-versions <= 7.4 && matrix.composer-options == '' }}
+    - if: ${{ matrix.php-versions >= '7.1' && matrix.php-versions < '8.0' && matrix.composer-options == '' }}
       name: Static analysis
       run: |
         composer require --dev nette/neon "^3.0"
         composer require --dev phpstan/phpstan "0.12.45"
         vendor/bin/phpstan analyse src
 
+    #static compatibility-check for all versions
+    #Only needs to be run on 1 php-version to check for all versions
```
[the remark this answers is not in the document]
Comment (Zombaya) [reply .github/workflows/tests.yml:75]: If there is 100% code coverage, this will be redundant, yes.  

When I added the tool, only false positives were detected, so in that regard this tool does not add much value to the project as it stands.

However, I think the output from the tool is still useful in case some new code is using non-bc-compatible syntax or function-arguments.  I think this output might be more clear than a failing unittest, where you as a developer need to be aware what exactly is not valid in all versions of php.

I've used this tool in other projects, which did have non-compatible code.  There it helped to figure out which code needed some refactoring.

If you decide the tool does not bring much value, you can simply drop 7c51a9ea79fd6dc435dd9e2b0d1e94b0743ba092 from the PR as it was added in a seperate commit.  Worst case my effort lead to a validation that all code is valid in php 5.5-8.1 :slightly_smiling_face:.

File: src/Crypto/AesGcmDecryptingStream.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (Zombaya) [reply src/Crypto/AesGcmDecryptingStream.php:86]: I agree that using the comments is rather ugly but it's the only way to ignore specific sections of code.

Maybe we could go for a middleground where we have multiple configuration-files:
* All rules, all files except the ones with exceptions
* All rules except false positive rule 1, single file which had the false positive
* All rules except false positive rule 2, single file which had the false positive
* ...

This way, we would ignore the false positive in a whole file, which might lead to a false negative in case a rule would trigger twice in a file with one false positive.

This would allow to have the bulk of the files linted with all rules and files with false positives would only have one rule ignored.

**Comment by stobrien89** [comment]
Hey @Zombaya,

I know it's been a while— sorry for the delay.  Could you rebase and remove the compatibility check? We've decided it's something we'll possibly revisit in the future.  Thanks again for all of the effort on this.

**Comment by Zombaya** [comment]
Hey @stobrien89,

I've rebased everything again, added some small fixes because of changed tests and removed the commit about php-compatibility-check.

I ran the check manually once more and it succeeded without problems.

If you ever want to re-integrate the tool, I made [a backup of the branch](https://github.com/Zombaya/aws-sdk-php/tree/phpcompatibilityChecker-backup) or you could always check [the commit itself](https://github.com/Zombaya/aws-sdk-php/commit/a83f6aa57746b3f5c4e48c6d4d0e1355918602bf).

File: tests/Crypto/Polyfill/AesGcmTest.php [hunk 6]
```diff
@@ -2618,9 +2618,8 @@ public function testCompat()
             $this->markTestSkipped('This test can only run on PHP 7.1');
             return;
         }
-        $ptLen = \random_int(0, 1024);
-        $aadLen = \random_int(0, 1024);
-        $i = 0;
+        $ptLen = \random_int(1, 1024);
+        $aadLen = \random_int(1, 1024);
```
Comment (Zombaya) [inline tests/Crypto/Polyfill/AesGcmTest.php:2622]: The reason the pipeline for this MR previously failed, was because `$aadLen` was 0, resulting in a failure when doing `$aad = \random_bytes($aadLen + $i);`.

This is now avoided by having the minimum-value of both lengths to be 1.

**Comment by Zombaya** [comment]
@stobrien89 , I'm finished for today.  I believe all warnings from php 8.1 about deprecated ways of using some functions or implicit type-conversions should be fixed, as well as deprecation-warnings from phpunit 9.x and I solved the very low possibility of a failed workflow because of generating an invalid stringlength.

I believe this MR is now ready again.  If you need any more changes or information, I'll be glad to help.

File: src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php [hunk 7]
```diff
@@ -114,7 +114,7 @@ public function __invoke()
                     }
                     if (empty($token)) {
                         if ($this->tokenFileReadAttempts < $this->retries) {
-                            sleep(pow(1.2, $this->tokenFileReadAttempts));
+                            sleep((int) pow(1.2, $this->tokenFileReadAttempts));
```
Comment (Zombaya) [inline src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php:117]: I've kept the result of the code the same, but it does lose some precision which might be wanted.

An alternative fix would be using `usleep()`, to keep a higher resolution.

```php 
usleep((int) (1000*1000*pow(1.2, $this->tokenFileReadAttempts)));
```
(Same goes for the same change in other places where this was changed.)

**Review by stobrien89 — CHANGES_REQUESTED** [review]

File: tests/CloudFront/fixtures/test2.pem [hunk 8]
```diff
@@ -0,0 +1,27 @@
+-----BEGIN RSA PRIVATE KEY-----
```
[the remark this answers is not in the document]
Comment (Zombaya) [reply tests/CloudFront/fixtures/test2.pem]: I've replaced this key by generating a new key in memory during each test.

File: .changes/nextrelease/php8 [hunk 9]
```diff
@@ -0,0 +1,7 @@
+[
+    {
+        "type": "enhancement",
+        "category": "",
+        "description": "Add support for php 8.x"
```
[the remark this answers is not in the document]
Comment (Zombaya) [reply .changes/nextrelease/php8]: I've replaced it by your suggestion.

**Comment by Zombaya** [comment]
@stobrien89 , I fixed all your latest remarks and rebased everything on master once more.

However, I'm running into a new issue with the CI regarding the test [`Aws\Test\CloudFront\SignerTest::testBadPrivateKeyPath()`](https://github.com/Zombaya/aws-sdk-php/runs/6467922428?check_suite_focus=true).  

It's throwing some sort of error related to openssl, but I'm not being to reproduce the error locally.  Nor the underlying code nor the testcode have changed fundamentally with this PR, so I'm a bit out my depth here on how to fix this.

**Comment by divinity76** [comment]
PS aws-sdk-php seems to be affected by https://github.com/PHPCompatibility/PHPCompatibility/issues/1339

File: src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php (hunk 7 above)
Comment (allemas) [reply src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php]: I do not know if you have seen but in the file aws-sdk-php/src/Credentials/InstanceProfileProvider.php there is the same fix to do in line 262 : 

```
    private function handleRetryableException(
        \Exception $e,
        $retryOptions,
        $message
    ) {
        $isRetryable = true;
        if (!empty($status = $this->getExceptionStatusCode($e))
            && isset($retryOptions['blacklist'])
            && in_array($status, $retryOptions['blacklist'])
        ) {
            $isRetryable = false;
        }
        if ($isRetryable && $this->attempts < $this->retries) {
            sleep((int) pow(1.2, $this->attempts));            <-----
        } else {
            throw new CredentialsException($message);
        }
    }
```

**Comment by stobrien89** [comment]
Hi @Zombaya,

So sorry for the delayed response— I missed your last message.  I'll take another look.  Thanks again for your patience!

File: src/Api/Serializer/JsonBody.php [hunk 10]
```diff
@@ -29,7 +29,7 @@ public function __construct(Service $api)
     public static function getContentType(Service $service)
     {
         return 'application/x-amz-json-'
-            . number_format($service->getMetadata('jsonVersion'), 1);
+            . number_format(($version = $service->getMetadata('jsonVersion')) !== null ? $version : 0.0, 1);
```
Comment (stobrien89) [inline src/Api/Serializer/JsonBody.php:32]: Could you make this multiple lines?

File: tests/Polyfill/PHPUnit9/PHPUnitCompatTrait.php [hunk 11]
```diff
@@ -0,0 +1,130 @@
...
+                $stack[1]['class'],
+                $stack[1]['function'],
+                $type
+            )
+        );
+    }
+
+    public function assertArraySubset($subset, $array, $checkForObjectIdentity = false, $message = '')
+    {
+        if ( ! (\is_array($subset) || $subset instanceof ArrayAccess)) {
```
Comment (stobrien89) [inline tests/Polyfill/PHPUnit9/PHPUnitCompatTrait.php:112]: Can you change the spacing here and for the line below to `!(\is_array...`?

File: tests/bootstrap.php [hunk 12]
```diff
@@ -3,17 +3,21 @@
 date_default_timezone_set('UTC');
 
 // Include the composer autoloader
-$loader = require __DIR__ . '/../vendor/autoload.php';
+$loader = require __DIR__.'/../vendor/autoload.php';
 
-if (!class_exists('\PHPUnit\Framework\Constraint\RegularExpression')) {
+if ( ! defined('PHPUNIT_COMPOSER_INSTALL')) {
```
Comment (stobrien89) [inline tests/bootstrap.php:8]: Can you change the not operator spacing in this file as well? i.e. (!class_exists...

File: .github/workflows/tests.yml [hunk 13]
```diff
@@ -76,6 +90,6 @@ jobs:
         make package
 
     #generate code coverage
-    - if: ${{ matrix.php-versions == '7.1' && matrix.composer-options == '' }}
+    - if: ${{ (matrix.php-versions == '7.1' || matrix.php-versions == '8.0') && matrix.composer-options == '' }}
```
[the remark this answers is not in the document]
Comment (stobrien89) [reply .github/workflows/tests.yml:83]: Let's just upgrade the version here if possible.

**Review by stobrien89 — CHANGES_REQUESTED** [review]
Left a few comments, but I think we're getting close :)

File: src/S3/S3Client.php [hunk 14]
```diff
@@ -429,7 +429,7 @@ public function __construct(array $args)
      */
     public static function isBucketDnsCompatible($bucket)
```
[the remark this answers is not in the document]
Comment (Zombaya) [reply src/S3/S3Client.php:430]: I've added a type check and some more cases to the unittest.

File: tests/CloudFront/UrlSignerTest.php [hunk 15]
```diff
@@ -28,30 +31,28 @@ public function testCreatesUrlSignersForHttp()
...
 
-        $this->assertContains("Key-Pair-Id={$kp}", $url);
+        $this->assertStringContainsString("Key-Pair-Id={$this->kp}", $url);
         $this->assertStringStartsWith(
             "http://abc.cloudfront.net/images/image.jpg?color=red&Expires={$ts}&Signature=",
             $url
         );
         $urlObject = new Uri($url);
-        $query = \GuzzleHttp\Psr7\Query::parse($urlObject->getQuery());
+        $query     = \GuzzleHttp\Psr7\Query::parse($urlObject->getQuery());
```
[the remark this answers is not in the document]
Comment (Zombaya) [reply tests/CloudFront/UrlSignerTest.php]: I assume @27pchrisl either configured his IDE to do this automatically or has the same preference as me, which is aligned `=`-signs :slightly_smiling_face: .

I've removed it for now and reverted to what it was.

**Comment by Zombaya** [comment]
I fixed all final remarks you had and rebased everything on master again.

I think the formatting-issues could have been avoided if there was a php-cs-fixer-configuration-file available and a lint-check in github-CI.  

I'm trying out some things to see if I can make a valuable contribution for this in [Zombaya/aws-sdk-php#4 php-cs-fixer](https://github.com/Zombaya/aws-sdk-php/pull/4). 
Please let me know if you think this would not be helpful so I avoid spending too much time on it.

**Comment by Zombaya** [comment]
I've rebased onto master again. 

I needed to modify `Aws\Test\S3\StreamWrapperV2ExistenceTest` to use the new `PhpUnitCompatTrait` and use the methods for expecting errors instead of the annotations.

File: tests/S3/StreamWrapperV2ExistenceTest.php [hunk 16]
```diff
@@ -9,6 +9,7 @@
 use Aws\S3\Exception\S3Exception;
 use Aws\S3\S3Client;
 use Aws\S3\StreamWrapper;
+use Aws\Test\Polyfill\PHPUnit\PHPUnitCompatTrait;
```
Comment (Zombaya) [inline tests/S3/StreamWrapperV2ExistenceTest.php:12]: This file was updated in my last rebase.

File: tests/EndpointParameterMiddlewareTest.php [hunk 17]
```diff
@@ -90,7 +90,7 @@ public function testCorrectlyOutputsHost(
         });
 
         $handler = $list->resolve();
-        $handler($command, new Request('POST', $endpoint));
+        $handler($command, new Request('POST', $endpoint))->wait(false);
```
[the remark this answers is not in the document]
Comment (Zombaya) [reply tests/EndpointParameterMiddlewareTest.php]: I found out why this was probably added.  

When running this test using PHP 8.0 and PHPUnit 9.x, this test is marked as a risky test because it does not run any assertions.  When adding `->wait(false)`, this disappears and the assertions are actually being done.

**Comment by Zombaya** [comment]
@stobrien89 , just wanted to let you know I'll not be available in the coming weeks, so will not be able to help with any rebasing. 

I'm very happy with the work on #2456 and will be implementing the result internally as soon as possible :slightly_smiling_face:.  Nice work:+1:!

File: src/S3/S3Client.php [hunk 18]
```diff
@@ -429,7 +429,11 @@ public function __construct(array $args)
...
     {
-        $bucketLen = strlen($bucket);
+        if (!is_string($bucket)) {
+            return false;
+        }
+
+        $bucketLen = $bucket !== null ? strlen($bucket) : 0;
```
Comment (SamRemis) [inline src/S3/S3Client.php:436]: This check is not necessary if we are checking for is_string above; it will never be null and always be a string, right?

File: tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php [hunk 19]
```diff
@@ -0,0 +1,141 @@
+<?php
+
```
Comment (SamRemis) [inline tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php:2]: Is there a reason we would use our own Polyfill instead of taking a dependency on something widely tested and maintained like https://github.com/Yoast/PHPUnit-Polyfills?

File: tests/CloudFront/UrlSignerTest.php [hunk 20]
```diff
@@ -28,30 +31,28 @@ public function testCreatesUrlSignersForHttp()
             'region'  => 'us-west-2',
             'version' => 'latest'
         ]);
-        $ts = time() + 1000;
-        $key = $_SERVER['CF_PRIVATE_KEY'];
-        $kp = $_SERVER['CF_KEY_PAIR_ID'];
+        $ts     = time() + 1000;
```
Comment (SamRemis) [inline tests/CloudFront/UrlSignerTest.php:34]: spacing

File: tests/CloudFront/UrlSignerTest.php [hunk 21]
```diff
@@ -61,23 +62,21 @@ public function testCreatesUrlSignersWithSpecialCharacters()
...
```
Comment (SamRemis) [inline tests/CloudFront/UrlSignerTest.php:65]: spacing

File: tests/CloudFront/UrlSignerTest.php [hunk 22]
```diff
@@ -61,23 +62,21 @@ public function testCreatesUrlSignersWithSpecialCharacters()
...
 
         $invalidUri = 'http://abc.cloudfront.net/images/éüàçµñåœŒ.jpg?query key=query value';
-        $uri = new Uri($invalidUri);
+        $uri        = new Uri($invalidUri);
```
Comment (SamRemis) [inline tests/CloudFront/UrlSignerTest.php:68]: spacing

File: tests/CloudFront/UrlSignerTest.php [hunk 23]
```diff
@@ -91,14 +90,14 @@ public function testCreatesUrlSignersWithCustomPolicy()
             'region'  => 'us-west-2',
             'version' => 'latest'
         ]);
-        $url = $client->getSignedUrl(array(
-            'url'    => 'http://abc.cloudfront.net/images/image.jpg',
-            'policy' => '{}',
-            'private_key' => $_SERVER['CF_PRIVATE_KEY'],
-            'key_pair_id' => $_SERVER['CF_KEY_PAIR_ID']
+        $url    = $client->getSignedUrl(array(
```
Comment (SamRemis) [inline tests/CloudFront/UrlSignerTest.php:93]: spacing (next three lines)

File: tests/ClientResolverTest.php [hunk 24]
```diff
@@ -222,19 +221,17 @@ public function testValidatesNotInvokeStringCallable()
             ]
         ]);
         $res = $r->resolve([], new HandlerList());
-        $this->assertInternalType('callable', $callableFunction);
+        $this->assertIsCallable($callableFunction);
         $this->assertSame(
-            '\Aws\test\ClientResolverTest::checkCallable',
+            '\Aws\Test\ClientResolverTest::checkCallable',
```
Comment (SamRemis) [inline tests/ClientResolverTest.php:226]: Isn't this lowercase?  It should work either way, but why change it?

File: tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php (hunk 19 above)
Comment (SamRemis) [reply tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php:2]: I'd think it's worth having as little code to maintain as possible by using the polyfill, especially when there's a dependency that does exactly that.  I'd prefer it, yes.  @stobrien89, do you agree? 

Also as a side note, sorry this is taking so long.  It's a huge PR and carefully looking at every single file over and over again is very time consuming.  Thank you for being patient, and I'll do my best to prioritize it higher.  If you don't see me respond for a bit, feel free to @ me to give me a notification.  That said, I'll try to look at this every day until it's merged.

Comment (stobrien89) [reply tests/Polyfill/PHPUnit4/PHPUnitCompatTrait.php:2]: @SamRemis @27pchrisl,

I definitely agree.  Especially with us looking forward to the next major version, having as little code to maintain as possible will be ideal.  Thanks again for all of the work on this @Zombaya and @27pchrisl!

**Comment by stobrien89** [comment]
@Zombaya, @27pchrisl,

I've rebased and updated tests for `RemoveUnusedServices` and #2459.  I've also fixed some of the warnings/risky tests that appear in 7.3+ and addressed @SamRemis's most recent comments.  I've attempted to push, but it looks like I'll need to be granted access.  Thanks again!

**Comment by Zombaya** [comment]
@stobrien89 , I've added you and the other contributors here as contributor to the project so you should be able to push to the branch.

Otherwise a second PR can be created to replace this one from your branch.

**Comment by RobinHoutevelts** [comment]
@stobrien89 Did you manage to get the work you did above (https://github.com/aws/aws-sdk-php/pull/2403#issuecomment-1191906911) into this PR?

**Comment by stobrien89** [comment]
Hi @Zombaya, @27pchrisl, @RobinHoutevelts,

Apologies for the delay.  Just pushed up the changes I mentioned in my last comment, including some changes related to https://github.com/aws/aws-sdk-php/pull/2498.  

From here, I think the next step would be to take a dependency on https://github.com/Yoast/PHPUnit-Polyfills.  @SamRemis and I have discussed and with the next major version on the horizon, we'd rather not have another component to maintain.  Thanks!

**Comment by Zombaya** [comment]
@stobrien89, @SamRemis,  I've added a dependency on `yoast/phpunit-polyfills` and `dms/phpunit-arraysubset-asserts`.

`dms/phpunit-arraysubset-asserts` was added since the removed `$this->assertArraySubset()` is used in some places and is not provided by `yoast/phpunit-polyfills`. It is [directly recommended](https://github.com/Yoast/PHPUnit-Polyfills#removed-functionality-without-phpunit-native-replacement) by `yoast/phpunit-polyfills` though.

# Strategy
* Classes which use no deprecated PHPUnit-assertions extend `PHPUnit\Framework\TestCase`
* Classes which use a deprecated PHPUnit-assertion provided by `yoast/phpunit-polyfills` extend `Yoast\PHPUnitPolyfills\TestCases\TestCase`
* Traits which use deprecated PHPUnit-assertions use the specific Trait provided by yoast which provide the used assertion
* Classes which use the deprecated method `assertArraySubset()` use the Trait provided by `dms/phpunit-arraysubset-asserts`

# Base TestCase
I opted to only use `Yoast\PHPUnitPolyfills\TestCases\TestCase` as a base-class for testcases which actually use deprecated methods.  I think this makes it more clear which testcases which are more interesting to refactor or to check in case the support for php 5.5 and PHPUnit 5 is dropped.

The other option would be that every test extends this TestCase. This way you do not need to be very aware of what methods are deprecated when writing new TestCases.

I felt that the first option was preferable.

# Main changes

## Different methodnames for setUp(), tearDown(), ...
The library by Yoast provides different methodnames for fixtures than what was used in the `PhpUnitCompatTrait`.

```diff
-- function _setUp() {}
++ function set_up() {}

-- function _tearDown() {}
++ function tear_down() {}

-- public static function _setUpBeforeClass()
++ public static function set_up_before_class()

-- public static function _tearDownAfterClass()
++ public static function tear_down_after_class()
```

## $this->readAttribute() replaced by $this->getPropertyValue()
`readAttribute()` was part of `PhpUnitCompatTrait`.  This has been replaced by [the method provided by Yoast](https://github.com/Yoast/PHPUnit-Polyfills#yoastphpunitpolyfillshelpersassertattributehelper).
```diff
-- $this->assertArrayHasKey('s3', $this->readAttribute($p, 'manifest'));
++ $this->assertArrayHasKey('s3', $this->getPropertyValue($p, 'manifest'));
```

## Replaced $this->expectNotToPerformAssertions() by $this->addToAssertionCount(1)
`expectNotToPerformAssertions()` does not exist in older versions of PHPUnit. It is also not provided by `yoast/phpunit-polyfills`.
That's why I opted to use `$this->addToAssertionCount(1)`, to avoid problems with warnings of tests with no assertions.

I've left a comment in place to eventually replace it again with `expectNotToPerformAssertions()`.

Other options would be writing a new compatibilityTrait inside our library, try to get a PR merged with `yoast/phpunit-polyfills` so
that it provides the method or rewriting the tests so that they always do an assertion.

```diff
-- $this->expectNotToPerformAssertions();
++ $this->addToAssertionCount(1); // To be replaced with $this->expectNotToPerformAssertions();
```

I could not find a lot of documentation on the method.  I couldn't find it in the docs for example. Some documentation I found:

* [YouTrack jetbrains WI-66119](https://youtrack.jetbrains.com/issue/WI-66119/New-inspection-PhpUnit-test-did-not-perform-any-assertions)
* [Stackoverflow: PHPUnit passing a test with no assertions within config](https://stackoverflow.com/questions/6666242/phpunit-passing-a-test-with-no-assertions-within-config)
* [Github PHPUnit PR#2898 Added expectNotToPerformAssertions method](https://github.com/sebastianbergmann/phpunit/pull/2898)

**Comment by devicenull** [comment]
Was any further progress made here?  We've started to run into issues with PHP 8.1

**Comment by RobinHoutevelts** [comment]
> Also as a side note, sorry this is taking so long. It's a huge PR and carefully looking at every single file over and over again is very time consuming. Thank you for being patient, and I'll do my best to prioritize it higher. **If you don't see me respond for a bit, feel free to @ me to give me a notification.** That said, I'll try to look at this every day until it's merged.

@SamRemis , consider this a friendly notification 👼 

Thanks everyone for all the hard work so far!

**Comment by SamRemis** [comment]
@RobinHoutevelts thanks for the ping :) since the last update on Tuesday or Wednesday I've been working through this about 40 files a day, I'm gonna try to finish it up tomorrow or monday.  Only issue I've found so far is a missing space, which I won't block on, so it's getting close :)

**Comment by SamRemis** [comment]
Just to update, I have about 20 files left to go through, which I won't be able to do before today's release, but I should be able to finish today.  Assuming I find no issues, which I haven't yet in the first 140 files, I will be able to merge tonight and this should go out with tomorrow's release.

**Review by SamRemis — APPROVED** [review]

**Review by stobrien89 — APPROVED** [review]

**Comment by roborourke** [comment]
Absolute legend @Zombaya

**Comment by Zombaya** [comment]
@SamRemis, @stobrien89, you made me one happy camper by getting this merged and released today!

Many thanks and much kudos for the effort you spent and the thorough review you did multiple times.  I was impressed with the level of detail you went over everything, as well as the respectfulness of the notes when something was not quite correct.

Small shout-out to @27pchrisl for initiating the work on this PR and continuing to help after reviews have been made. 

I think it's safe to say this was as PR me and a lot of others were all looking forward to be merged into master :slightly_smiling_face:.
