### PR TITLE
bugfix empty token file

### LINKED ISSUE #2164: AssumeRoleWithWebIdentityCredentialProvider: Missing or locked AWS_WEB_IDENTITY_TOKEN_FILE
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution

**Describe the bug**
We get sporadically the following failure on assumeRoleWithWebIdentity():

    [WebIdentityToken] must be a string or an object that implements __toString(). Found bool(false) (0)

*Method: Aws\Credentials\AssumeRoleWithWebIdentityCredentialProvider->__invoke()*

```file_get_contents()``` return's ```bool(false)```.

It seems that the AWS_WEB_IDENTITY_TOKEN_FILE is locked or missing during loading of the file content. I don't know exactly what happens, when the token-file is updated with a new token but there seems to be a kind of race condition.

**Version of AWS SDK for PHP?**
v3.166.0

**Version of PHP (`php -v`)?**
PHP 7.3.25

**To Reproduce (observed behavior)**

I was able to reproduce it with an empty token, which leads to a similar problem:

First create an empty token file and set needed ENV's:

    touch /tmp/token.file
    export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/token.file
    export AWS_ROLE_ARN=arn:aws:iam::123456789123:policy/AnyPolicy

Code:
```php
use Aws\Credentials\CredentialProvider;
use GuzzleHttp\Promise\Coroutine;

$provider = CredentialProvider::assumeRoleWithWebIdentityCredentialProvider([]);
/** @var Coroutine $coroutine */
$coroutine = $provider();
$coroutine->then(function () {
    echo 'success';
})->otherwise(function (\RuntimeException $e) {
    echo sprintf('%s: %s', $e->getCode(), $e->getMessage());
});
```
Failure:

    [WebIdentityToken] expected string length to be >= 4, but found string length of 1 (0)

**Expected behavior**
My guess is that the token file is sporadically locked or missing when it is in exchange.
I think this should lead to an AwsException with code "InvalidIdentityToken" to trigger the retry mechanism.

### PR DESCRIPTION
**Pull request by SamRemis**
*Issue #, if available:*
fix #2164
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php [hunk 1]
```diff
@@ -108,6 +108,9 @@ public function __invoke()
                         }
                         $token = file_get_contents($this->tokenFile);
                     }
+                    if (empty($token)) {
+                        throw new CredentialsException("InvalidIdentityToken from file: {$this->tokenFile}");
+                    }
```
Comment (tobiashaase) [inline src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php:113]: Hello @SamRemis,
thank you very much for your quick response.

I think this change just leads to another failure message?
In addition this should trigger a retry in my opinion.

I would prefer something like this at line 129 before calling assumeRoleWithWebIdentity():

```php
if (empty($assumeParams['WebIdentityToken'])) {
    throw new AwsException(
        "Empty InvalidIdentityToken",
        null,
        [
            'code' => 'InvalidIdentityToken',
        ]
    );
}
```

Best regards
Tobias

Comment (SamRemis) [reply src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php:113]: Hi @tobiashaase,

I definitely agree that is the proper behavior; the reason I implemented it this way was just to get a quick fix in while I can do a bit more investigating.  I will need to look into how other SDKs are handling retries to make sure our behavior lines up and is appropriate.  I hesitate to copy the logic from below since the retries are meant for actual guzzle calls made by the client, so it's difficult to say how retries on reading the file should behave.  If there isn't a standard already established, I can make one :)

-Sam

Comment (tobiashaase) [reply src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php:113]: Ok - I understand. Thank very you.

**Review by ajredniwja — APPROVED** [review]
