### PR TITLE
Pass endpoint prefix rather than service identifier to EndpointProvider

### LINKED ISSUE #1189: AppStream 2.0 createStreamingURL -- Incorrect Endpoint
I am attempting to write a PHP script that uses createStreamingURL() to shuffle users over to AppStream to run apps. However, when I attempt to do this, I am seeing the following in the debug output:

```
Fatal error:  Uncaught exception 'Aws\Appstream\Exception\AppstreamException' with message 'Error executing "CreateStreamingURL" on "https://appstream.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://appstream.us-east-1.amazonaws.com` resulted in a `404 Not Found` response:
<UnknownOperationException/>

 Unable to parse error information from response - Error parsing JSON: unexpected character'

exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://appstream.us-east-1.amazonaws.com` resulted in a `404 Not Found` response:
<UnknownOperationException/>

' in /home/ubuntu/workspace/appstream-auth/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /home/ubuntu/workspace/appstream-auth/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/ubuntu/workspace/appstream-auth/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHtt in /home/ubuntu/workspace/appstream-auth/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192
```

If you notice, the URL it is sending the request to is **appstream.us-east-1.amazonaws.com**. Invoking the same call using the CLI with debugging turned on shows something different -- and it works:

```
2017-02-19 21:17:40,079 - MainThread - botocore.hooks - DEBUG - Event request-created.appstream2.CreateStreamingURL: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f0bb3cf5410>>
2017-02-19 21:17:40,080 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-02-19 21:17:40,080 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-amz-json-1.1
host:appstream2.us-east-1.amazonaws.com
x-amz-date:20170219T211740Z
x-amz-target:PhotonAdminProxyService.CreateStreamingURL

content-type;host;x-amz-date;x-amz-target
1cf4403fe47d8a04d4bae8ac1702fd31a6cb0dbb7b4416734f51fc445bcc98c5
2017-02-19 21:17:40,080 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20170219T211740Z
20170219/us-east-1/appstream/aws4_request
dd06cfd0468c5baee613c52d113014f643462a407de176ac6592dff97056ee8d
2017-02-19 21:17:40,081 - MainThread - botocore.auth - DEBUG - Signature:
fe1ed79fe16808c1144ea58913c7a82326bc07808f9688782bb193340306ae42
2017-02-19 21:17:40,089 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-02-19 21:17:40,090 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): appstream2.us-east-1.amazonaws.com
2017-02-19 21:17:40,316 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 200 448
```

You will notice here, using **appstream_2_.us-east-1.amaazonaws.com**, that the CLI gets a 200 and happily returns a JSON object containing the requested streaming URL.

Please investigate. I tried mucking about in the SDK code trying to get it to point at appstream2, but that proved to be more difficult than originally thought. 

Thank you!
Corey

[php-debug.txt](https://github.com/aws/aws-sdk-php/files/786215/php-debug.txt)
[cli-debug.txt](https://github.com/aws/aws-sdk-php/files/786216/cli-debug.txt)

### LINKED ISSUE #1190: Undefined index: partitionEndpoint
Hi guys,

When I instantiate ShieldClient(), I got an error :
=> Undefined index: partitionEndpoint

I have correctly specified region, version and credentials but it seems you have an issue in your SDK. To fix the problem, you need to add `'partitionEndpoint' => 'aws-global'` in your endpoints.json.php field for ShieldClient.

You can also do like that :
` if(!isset($this->data['services'][$service]['partitionEndpoint'])){
            return 'aws-global';
        }`
In the file => /aws-sdk-php/src/Endpoint/Partition.php (line 169)

Regards,
Aymeric

### PR DESCRIPTION
**Pull request by jeskew**
This PR changes the internals of `Aws\ClientResolver::_apply_endpoint_provider` to pass the endpoint prefix rather than the service identifier to the EndpointProvider. This would resolve #1189 as `endpoints.json` keys the AppStream service metadata as `appstream2` rather than `appstream`.

Additionally, this PR modifies the `isServicePartitionGlobal` check in `Aws\Endpoint\Partition` to only return `true` if the service defines a partition endpoint. This would resolve #1190 

/cc @cjyclaire

### CODE REVIEW

File: src/Endpoint/Partition.php [hunk 1]
```diff
@@ -161,7 +161,8 @@ private function resolveRegion($service, $region)
     private function isServicePartitionGlobal($service)
     {
         return isset($this->data['services'][$service]['isRegionalized'])
-            && false === $this->data['services'][$service]['isRegionalized'];
+            && false === $this->data['services'][$service]['isRegionalized']
+            && isset($this->data['services'][$service]['partitionEndpoint']);
```
Comment (cjyclaire) [inline src/Endpoint/Partition.php]: Looks good, just curious, is this fix a work-around for some unexpected global endpoints or this is a normal behavior?

File: tests/Endpoint/PartitionTest.php [hunk 2]
```diff
@@ -338,6 +365,12 @@ public function signatureVersionProvider()
                         'puff' => [],
                     ],
                 ],
+                'sdb' => [
```
Comment (cjyclaire) [inline tests/Endpoint/PartitionTest.php]: Great, it would also help reduce the time when `changelogBuilder` is trying to replacing string : )

File: src/Endpoint/Partition.php (hunk 1 above)
Comment (jeskew) [inline src/Endpoint/Partition.php]: I've seen warnings emitted in the `aws-sdk-php-symfony` build. My understanding of the endpoints.json format when writing the `Partition` class was that a `partitionEndpoint` would always be present if a service self-reported as not regionalized. That doesn't seem to be true in all cases.

Comment (cjyclaire) [inline src/Endpoint/Partition.php]: Hmm, that's true, same as how I figured. Anyways, this looks good : )

**Comment by cjyclaire** [comment]
LGTM :shipit:
