### PR TITLE
Catch generic exceptions when assuming role using web identity creds

### LINKED ISSUE #1891: Undefined method named "getAwsErrorCode" of class "InvalidArgumentException"
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.112.31

### Version of PHP (`php -v`)?
7.1.32

### What issue did you see?
`Attempted to call an undefined method named "getAwsErrorCode" of class "InvalidArgumentException".`

Shouldn't there be a check if the `getAwsErrorCode` exists?

https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php#L113

### PR DESCRIPTION
**Pull request by diehlaws**
Fix #1891 

*Description of changes:*
Modified existing catch block for `assumeRoleWithWebIdentity` to catch AwsExceptions, added new catch block to handle generic exceptions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php [hunk 1]
```diff
@@ -125,6 +126,12 @@ public function __invoke()
                             $e
                         );
                     }
+                } catch (\Exception $e) {
+                    throw new CredentialsException(
+                        "Error retrieving web identity credentials: " . $e->getMessage()
+                        . " (" . $e->getCode() . ")"
+                    );
+
```
Comment (howardlopez) [inline src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php]: Style nitpick: unnecessary line

File: tests/Credentials/AssumeRoleWithWebIdentityCredentialProviderTest.php [hunk 2]
```diff
@@ -196,6 +196,43 @@ public function testThrowsExceptionWhenRetrievingAssumeRoleCredentialFails()
         }
     }
 
+    /**
+     * @expectedException \Aws\Exception\CredentialsException
+     * @expectedExceptionMessage Error retrieving web identity credentials: Found 1 error while validating the input provided for the AssumeRoleWithWebIdentity operation:
+    [RoleArn] expected string length to be >= 20, but found string length of 11 (0)
```
Comment (howardlopez) [inline tests/Credentials/AssumeRoleWithWebIdentityCredentialProviderTest.php]: `@expectedExceptionMessage` will match the start of the exception message, so you can probably just include the first line here, as it's enough to verify you're getting the exception message you want.

File: .changes/nextrelease/webidentityexceptions.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+[
+    {
+        "type": "bugfix",
+        "category": "CredentialProvider",
```
Comment (howardlopez) [inline .changes/nextrelease/webidentityexceptions.json]: The category targets the namespace (minus the `Aws`), so in this case it would be `Credentials`.
